### ISSUE TITLE
Special thanks

### ISSUE THREAD

**Issue by i3130002** [M-Devloo/Spring-boot-auth0-discriminator-multitenancy#11]
Dear @M-Devloo,

I am sincerely thankful for this project of yours. I was bashing my head against whatever I could to migrate from normal Long id to UUID id, and nothing seemed to work. I tried every combination of everything, from convertors to annotations and even string id as the entity type. Untill I saw your code which was simply using UUID in an entity with almost no excess code. 

I wanted to appreciate your work which lighten me up and guide me to resolve my problem.

Thanks a lot.

**Comment by M-Devloo** [comment]
Hi @i3130002,

Thank you very much for your kind words.
I am glad that the code could help you with your project.

Have a great day!

Michael
