### ISSUE TITLE
How can I test this

### ISSUE THREAD

**Issue by bernardgut** [M-Devloo/Spring-boot-auth0-discriminator-multitenancy#8]
Hello

I have successfully set this up to test it locally. However, I get a 403 when I want to test it: 

```
curl -X POST http://localhost:3000/create -H 'Content-Type: application/json' -d '{"name":"now"}'
{"timestamp":"2021-07-25T11:10:24.669+00:00","status":403,"error":"Forbidden","message":"","path":"/create"}%
```

I know it is something with the jwt token. I am pretty new to those and am not very familiar with these... Can you provide with an easy way to test this ?

Thanks

**Comment by M-Devloo** [comment]
Good morning @bernardgut,

The tool provides a default created Auth0 configuration that can not be used by others. 
You will always receive a 403 as the application requires a valid JWT token to access the api.

To validate the application on its own, you can follow the official Auth0 documentation:
[Auth0 - Spring Security 5 documentation](https://auth0.com/docs/quickstart/backend/java-spring-security5)
The great thing is that you can skip the Java implementation part as is already done for you! 😄 

- Add your Auth0 audience & issuer-url to the application.yml file
- Start up the application
- The server is now up and running to receive requests

Next step is to configure your client
[Auth0 - clients](https://auth0.com/docs/quickstart/backend/java-spring-security5/02-using).

- You have to obtain the access token. This application is implemented with single-page applications in mind. E.g. [Angular](https://auth0.com/docs/quickstart/spa/angular)
- When you receive your access token, you can provided it as a bearer token in your request
- You will no longer receive a forbidden (403) due your request is now authenticated.

Hope this helps, have a great day

**Comment by bernardgut** [comment]
Thanks for the quick answer

One thing I noticed is that you segregate your tenants based on the `sub` claim. Is that on purpose ? 
EG.in TenantAssistance.java :

```
 return Optional.ofNullable(SecurityContextHolder.getContext().getAuthentication())
        .filter(authentication -> authentication instanceof JwtAuthenticationToken)
        .map(authentication -> (JwtAuthenticationToken) authentication)
        .map(JwtAuthenticationToken::getName)
        .orElseThrow(() -> new UnknownTenantException("Tenant is empty"));
```

From somewhere I saw yesterday in the docs:
>JwtAuthenticationToken::getName by default returns the value of the `sub` claim. 

which from my understanding would not be a correct tenant discriminator (?)

I personally changed the above to

```
  public static String resolveCurrentTenantIdentifier() {
    String tenant = Optional.ofNullable(SecurityContextHolder.getContext().getAuthentication())
            .filter(authentication -> authentication instanceof JwtAuthenticationToken)
            .map(authentication -> (JwtAuthenticationToken) authentication)
            .get().getToken().getClaim(TenantEntity.TENANT_ID_PROPERTY_NAME);
    if(tenant.isEmpty()) throw new UnknownTenantException("Tenant is empty");
    return tenant;
```

And then added a `tenant_id` claim to my token.It seems to work but I am not sure if this is intended to be used like this.

cheers and have a good day

**Comment by M-Devloo** [comment]
Hi @bernardgut, the `JwtAuthenticationToken::getName`returns the Auth0 ID which is an unique ID e.g. `auth0|55b53f66-6d1e-48b2-a0d2-8444953b202e`. Due to the uniqueness, this was chosen to be a tenant identifier.

As stated in the [Auth0 documentation](https://auth0.com/docs/tokens/json-web-tokens/json-web-token-claims) `sub` is one of the seven reserved claims that are not required. But Auth0 does provide the Subject of the JWT (the user) as value for this claim.

There was no real reason to specifically use the `sub` claim other than it provides a unique user ID. :-)

You are freely to choose which tenant identifier you want to implement. If you prefer to add a custom claim to your token and you can guarantee the uniqueness for each tenant, feel free to switch it around.

Best regards,

Michael

**Comment by M-Devloo** [comment]
Move the documentation to the README.md
